import {
  AsaImportReviewStatus,
  DemonstrativeStatus,
  ValidationStatus,
  createEntityId,
  type Demonstrative,
} from '@asa/domain';

export function createSampleDemonstrative(): Demonstrative {
  return {
    id: createEntityId('DEM'),
    convenioCode: 'DEMO',
    convenioName: 'Convenio Demonstracao',
    payment: {
      id: createEntityId('PAY'),
      convenioCode: 'DEMO',
      convenioName: 'Convenio Demonstracao',
      paymentDate: '2026-08-17',
      competence: '2026-08',
      totalAmountCents: 47730,
      externalIdentifier: 'DEMO-2026-08-17-001',
      batchIdentifier: 'LOTE-DEMO-08',
    },
    status: DemonstrativeStatus.WAITING_MANUAL_ASA_IMPORT,
    portalAmountCents: 47730,
    demonstrativeAmountCents: 47730,
    guideCount: 2,
    guides: [
      {
        id: createEntityId('GUI'),
        numeroGuia: '000123456789',
        paciente: 'Ana Pereira',
        dataAtendimento: '2026-08-12',
        procedures: [
          {
            id: createEntityId('PROC'),
            guideNumber: '000123456789',
            codigoOriginal: '041301234',
            codigoASA: '041301240',
            descricao: 'Consulta ambulatorial',
            quantidade: 1,
            valorCents: 38000,
            glosaCents: 0,
            valorAuxiliaresCents: [0, 0, 0],
            valorInstitucionalCents: 0,
            dataAtendimento: '2026-08-12',
            pacienteNome: 'Ana Pereira',
            filme: '',
            codGlosa: '',
            originalData: {},
            transformations: [
              {
                originalCode: '041301234',
                asaCode: '041301240',
                matched: true,
                mappingSource: 'demo-fixture',
              },
            ],
          },
          {
            id: createEntityId('PROC'),
            guideNumber: '000123456789',
            codigoOriginal: '030101007',
            codigoASA: '030101007',
            descricao: 'Taxa de sala',
            quantidade: 1,
            valorCents: 4500,
            glosaCents: 0,
            valorAuxiliaresCents: [0, 0, 0],
            valorInstitucionalCents: 0,
            dataAtendimento: '2026-08-12',
            pacienteNome: 'Ana Pereira',
            filme: '',
            codGlosa: '',
            originalData: {},
            transformations: [
              {
                originalCode: '030101007',
                asaCode: '030101007',
                matched: true,
                mappingSource: 'demo-fixture',
              },
            ],
          },
        ],
      },
      {
        id: createEntityId('GUI'),
        numeroGuia: '000987654321',
        paciente: 'Bruno Lima',
        dataAtendimento: '2026-08-13',
        procedures: [
          {
            id: createEntityId('PROC'),
            guideNumber: '000987654321',
            codigoOriginal: '030102002',
            codigoASA: '030102002',
            descricao: 'Exame complementar',
            quantidade: 1,
            valorCents: 5230,
            glosaCents: 0,
            valorAuxiliaresCents: [0, 0, 0],
            valorInstitucionalCents: 0,
            dataAtendimento: '2026-08-13',
            pacienteNome: 'Bruno Lima',
            filme: '',
            codGlosa: '',
            originalData: {},
            transformations: [
              {
                originalCode: '030102002',
                asaCode: '030102002',
                matched: true,
                mappingSource: 'demo-fixture',
              },
            ],
          },
        ],
      },
    ],
    originalFiles: [],
    processedFiles: [],
    asaFile: null,
    validation: {
      status: ValidationStatus.VALIDATED,
      portalAmountCents: 47730,
      demonstrativeAmountCents: 47730,
      asaAmountCents: 47730,
      guideCount: 2,
      duplicateGuides: [],
      missingTussMappings: [],
      issues: [],
    },
    timeline: [],
    importReview: {
      status: AsaImportReviewStatus.PENDING,
      expectedAmountCents: 47730,
      importedAmountCents: null,
      differenceAmountCents: null,
      notes: null,
      updatedAt: null,
    },
    createdAt: '2026-08-28T12:00:00.000Z',
    updatedAt: '2026-08-28T12:00:00.000Z',
  };
}
